# Generated by Django 5.1.5 on 2025-02-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankpredictor', '0002_answersheet_question_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersheet',
            name='question_no',
        ),
    ]
