# Generated by Django 5.1.5 on 2025-02-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankpredictor', '0003_remove_answersheet_question_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='question_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
