# Generated by Django 5.1.5 on 2025-02-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankpredictor', '0005_slots_department_topper_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatescore',
            name='percentile',
        ),
        migrations.AddField(
            model_name='candidatescore',
            name='sheet_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
