# Generated by Django 5.1.5 on 2025-02-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankpredictor', '0006_remove_candidatescore_percentile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatescore',
            name='normalized_rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidatescore',
            name='rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
