# Generated by Django 5.1.5 on 2025-02-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankpredictor', '0007_candidatescore_normalized_rank_candidatescore_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='shift',
            field=models.CharField(blank=True, choices=[('FORENOON', 'FORENOON'), ('AFTERNOON', 'AFTERNOON')], max_length=20, null=True),
        ),
    ]
