# Generated by Django 5.1.5 on 2025-02-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankpredictor', '0008_alter_slots_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='question_Id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
