# Generated by Django 5.1.5 on 2025-02-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankpredictor', '0009_alter_answersheet_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='answer',
            field=models.CharField(max_length=500),
        ),
    ]
