# Generated by Django 5.1.5 on 2025-02-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankpredictor', '0010_alter_answersheet_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatescore',
            name='rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
